import React from 'react';
import { Download } from 'lucide-react';

const StudentPerformanceReport = () => {
    return (
        <div className="max-w-4xl mx-auto space-y-8 bg-white text-black p-8 rounded-xl shadow-xl">
            {/* Print/Download Header - This simulated a printable report page */}
            <div className="flex justify-between items-start border-b pb-8 border-gray-200">
                <div>
                    <h1 className="text-3xl font-bold text-blue-900">Academic Performance Report</h1>
                    <p className="text-gray-600 mt-2">Fall 2025 • Computer Science Department</p>
                </div>
                <button className="flex items-center gap-2 bg-blue-600 text-white px-4 py-2 rounded shadow hover:bg-blue-700 print:hidden">
                    <Download className="w-4 h-4" /> Download PDF
                </button>
            </div>

            <div className="grid grid-cols-2 gap-8">
                <div>
                    <h3 className="font-bold text-gray-500 uppercase text-xs tracking-wider mb-2">Student Details</h3>
                    <p className="font-bold text-lg">John Doe</p>
                    <p>ID: 700101</p>
                    <p>Section: A</p>
                </div>
                <div className="text-right">
                    <h3 className="font-bold text-gray-500 uppercase text-xs tracking-wider mb-2">Cumulative GPA</h3>
                    <p className="font-bold text-4xl text-blue-600">3.85</p>
                    <p className="text-sm text-green-600 font-bold">Excellent Standing</p>
                </div>
            </div>

            <div className="space-y-4">
                <h3 className="font-bold text-lg border-b border-gray-200 pb-2">Course Breakdown</h3>
                <table className="w-full text-left">
                    <thead className="bg-gray-100 text-gray-600 text-xs uppercase">
                        <tr>
                            <th className="px-4 py-2">Course</th>
                            <th className="px-4 py-2">Assignments</th>
                            <th className="px-4 py-2">Quizzes</th>
                            <th className="px-4 py-2">Midterm</th>
                            <th className="px-4 py-2">Total</th>
                            <th className="px-4 py-2">Grade</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-200">
                        <tr>
                            <td className="px-4 py-3 font-bold">Intro to AI</td>
                            <td className="px-4 py-3">88%</td>
                            <td className="px-4 py-3">92%</td>
                            <td className="px-4 py-3">85%</td>
                            <td className="px-4 py-3 font-bold">88.5%</td>
                            <td className="px-4 py-3 text-green-600 font-bold">A</td>
                        </tr>
                        <tr>
                            <td className="px-4 py-3 font-bold">Data Structures</td>
                            <td className="px-4 py-3">75%</td>
                            <td className="px-4 py-3">80%</td>
                            <td className="px-4 py-3">70%</td>
                            <td className="px-4 py-3 font-bold">75.0%</td>
                            <td className="px-4 py-3 text-blue-600 font-bold">B+</td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div className="bg-gray-50 p-6 rounded-lg border border-gray-200">
                <h3 className="font-bold text-lg mb-4">Instructor Comments</h3>
                <p className="text-gray-700 italic">"John has shown consistent improvement in understanding complex algorithms. Participation in class discussions is commendable."</p>
                <p className="text-right text-gray-500 text-sm mt-4">- Dr. Alan Turing</p>
            </div>

            <div className="text-center text-xs text-gray-400 mt-12 print:fixed print:bottom-4 print:w-full">
                Generated by Inkless Academic System on Oct 28, 2025
            </div>
        </div>
    );
};

export default StudentPerformanceReport;
